---
- name: Backup configuration from network devices
  hosts: switches
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: your_username
    ansible_password: your_password
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Get running configuration
      cisco.ios.ios_config:
        backup: yes
      register: backup_result

    - name: Save configuration backup locally
      copy:
        content: "{{ backup_result.backup_path | lookup('file') }}"
        dest: "./backups/{{ inventory_hostname }}_backup.cfg"
